title: <p align="center"> Ahmed Kamel </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ahmed-kamel-2331a430/">LinkedIn</a> |
  <a href="https://github.com/AhmedKamelAli">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Worked Big Data Analytics team in Cex department @STC.
  <br>
  </p>



theme: jekyll-theme-minimal
